name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build, tag, and push image to Google Container Registry
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.APP_GCR_REPOSITORY }}:$IMAGE_TAG todo-app/
          docker build -f k8s/Dockerfile.mysql -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.JOB_GCR_REPOSITORY }}:$IMAGE_TAG k8s/
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.APP_GCR_REPOSITORY }}:$IMAGE_TAG
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.JOB_GCR_REPOSITORY }}:$IMAGE_TAG
